task: "classification"
model: "transformer"
data_window_len: null
pos_encoding: "learnable"
activation: "relu"
normalization_layer: "layer_norm"
freeze: false
seed: 73054772
preprocess:
  method: "noise-both-end" # "default" "noise-both-end", "noise-both-end-concat"
  width: 100
  step: 50
model:
  input_dim: 6 # time series data
  max_seq_len: 100
  dim_inp: 512
  dim_model: 2048
  num_heads: 8
  num_layers: 6
  dropout: 0.5
train:
  optimizer: "adam"
  criterion: "dice" # "dice" "cross_entropy", "dice"
  scheduler: null
  batch_size: 32
  epochs: 100
  lr: 0.0005
  weight_decay: 0.0
  momentum: 0.9
  