_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 51
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
